# Generated by Django 3.2.24 on 2024-02-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagetext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='uname',
        ),
    ]
