# Generated by Django 3.2.24 on 2024-03-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_organizationname_userprofile_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imagetext'),
        ),
    ]
