# Generated by Django 3.2.24 on 2024-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_task_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageText',
        ),
    ]
