# Generated by Django 3.2.24 on 2024-04-11 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagetext_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetext',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
