# Generated by Django 3.2.24 on 2024-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_image_imagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
