# Generated by Django 3.2.24 on 2024-04-17 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_completedparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('general_comments', models.TextField()),
                ('organization_feedback', models.TextField()),
                ('experience_feedback', models.TextField()),
                ('suggestions', models.TextField()),
                ('completed_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.completedparticipation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
