# Generated by Django 3.2.24 on 2024-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_imagetext_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='image\\*'),
        ),
    ]
