# Generated by Django 3.2.24 on 2024-04-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
