# Generated by Django 3.2.24 on 2024-02-23 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_imagetext_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='aadhaar',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pop',
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
