# Generated by Django 3.2.24 on 2024-03-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_auto_20240223_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('favorite_items', models.CharField(blank=True, max_length=255)),
                ('recent_activity', models.JSONField(blank=True)),
            ],
        ),
    ]
