# Generated by Django 3.2.24 on 2024-03-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240304_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_items',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recent_activity',
        ),
    ]
