# Generated by Django 3.2.24 on 2024-03-10 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240304_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='password',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='place',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='uname',
            new_name='interest',
        ),
        migrations.AddField(
            model_name='task',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
