# Generated by Django 3.2.24 on 2024-03-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.imagetext'),
        ),
    ]
