# Generated by Django 3.2.24 on 2024-03-21 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_location_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
